package com.vela.app.ui.miniapp

import android.util.Log
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Dashboard
import androidx.compose.material.icons.filled.ErrorOutline
import androidx.compose.material.icons.filled.MenuBook
import androidx.compose.material.icons.filled.OpenInNew
import androidx.compose.material.icons.filled.TouchApp
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FloatingActionButton
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.ListItem
import androidx.compose.material3.ListItemDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.vela.app.ai.AmplifierSession
import com.vela.app.ai.GenerationResult
import com.vela.app.ai.RendererGenerator
import com.vela.app.data.db.MiniAppRegistryEntity
import com.vela.app.data.repository.CapabilitiesGraphRepository
import com.vela.app.data.repository.MiniAppDocumentStore
import com.vela.app.events.EventBus
import com.vela.app.ui.components.MarkdownText
import com.vela.app.vault.VaultManager
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.flow.update
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import javax.inject.Inject

// ────────────────────────────────────────────────────────────────────────────────
// Shared data class — also used by RendererGenerator (Task 6)
// ────────────────────────────────────────────────────────────────────────────────

/**
 * Represents the current app theme for injection into `__VELA_CONTEXT__` and for
 * LLM prompt assembly in [RendererGenerator]. Passed as a value — not a Compose state.
 */
data class VelaTheme(
    val isDark: Boolean,
    /** RGB hex colour, e.g. `"#7C4DFF"`. */
    val primaryColor: String,
)

// ────────────────────────────────────────────────────────────────────────────────
// RendererState — drives what MiniAppContainer shows
// ────────────────────────────────────────────────────────────────────────────────

/**
 * A context-aware suggestion for what kind of mini app to build.
 * Generated by [MiniAppViewModel.suggestRendererTypes] using the file content.
 */
data class RendererSuggestion(
    val type: com.vela.app.ai.RendererType,
    /** Short, content-specific label, e.g. "Step-by-step guide" for a recipe. */
    val label: String,
    /** One sentence specific to this content, e.g. "Check off ingredients as you cook." */
    val description: String,
)

/**
 * Tracks the renderer lifecycle inside [MiniAppContainer].
 *
 * - [Loading]      — reserved; not used as the initial state after the blank-screen fix.
 * - [Ready]        — renderer HTML exists on disk; WebView loads it.
 * - [Fallback]     — no cached renderer yet; show a native Compose viewer + "Generate" FAB.
 * - [Building]     — renderer generation is in progress; show full-screen build log.
 * - [BuildFailed]  — generation failed; show error screen with retry option.
 */
sealed class RendererState {
    object Loading : RendererState()
    data class Fallback(val contentType: String, val content: String) : RendererState()
    data class Building(val rendererType: com.vela.app.ai.RendererType) : RendererState()
    data class Ready(val rendererFile: File) : RendererState()
    data class BuildFailed(
        val rendererType: com.vela.app.ai.RendererType,
        val cause: Throwable,
    ) : RendererState()
}

// ────────────────────────────────────────────────────────────────────────────────
// ViewModel — dependency carrier, one instance per screen destination
// ────────────────────────────────────────────────────────────────────────────────

@HiltViewModel
class MiniAppViewModel @Inject constructor(
    internal val documentStore: MiniAppDocumentStore,
    internal val eventBus: EventBus,
    internal val amplifierSession: AmplifierSession,
    internal val vaultManager: VaultManager,
    internal val rendererGenerator: RendererGenerator,
    private val capabilitiesRepo: CapabilitiesGraphRepository,
) : ViewModel() {

    /** Live capabilities graph — drives `__VELA_CONTEXT__.capabilities` updates. */
    val capabilities: StateFlow<List<MiniAppRegistryEntity>> =
        capabilitiesRepo.getAll()
            .stateIn(viewModelScope, SharingStarted.Eagerly, emptyList())

    private val _buildLog = MutableStateFlow("")
    val buildLog: StateFlow<String> = _buildLog.asStateFlow()

    /** Factory — creates one [VelaJSInterface] per (itemPath, contentType) pair. */
    fun createJsInterface(itemPath: String, contentType: String): VelaJSInterface =
        VelaJSInterface(
            documentStore    = documentStore,
            eventBus         = eventBus,
            amplifierSession = amplifierSession,
            vaultManager     = vaultManager,
            itemScopePath    = itemPath,
            contentType      = contentType,
        )

    /**
     * Returns the cached renderer HTML [File], or `null` if generation has not
     * happened yet (triggers fallback placeholder UI in [MiniAppContainer]).
     */
    fun getRendererFile(contentType: String): File? =
        vaultManager.resolve(".vela/renderers/$contentType/renderer.html")
            ?.takeIf { it.exists() }

    /**
     * Starts async renderer generation for [rendererType].
     * Streams tokens into [buildLog] as they arrive.
     * Returns the [GenerationResult] when complete.
     */
    suspend fun generateRenderer(
        itemPath: String,
        itemContent: String,
        contentType: String,
        theme: VelaTheme,
        layout: String,
        rendererType: com.vela.app.ai.RendererType,
    ): com.vela.app.ai.GenerationResult {
        _buildLog.value = ""
        return rendererGenerator.generateRenderer(
            itemPath     = itemPath,
            itemContent  = itemContent,
            contentType  = contentType,
            theme        = theme,
            layout       = layout,
            rendererType = rendererType,
            onToken      = { token -> _buildLog.update { it + token } },
        )
    }

    /**
     * Uses [amplifierSession] to generate context-aware mini app suggestions for [itemContent].
     * Falls back to static [RendererType] entries if the LLM call fails or returns unparseable output.
     */
    suspend fun suggestRendererTypes(
        itemContent: String,
        contentType: String,
    ): List<RendererSuggestion> {
        val fallback = com.vela.app.ai.RendererType.entries.map { type ->
            RendererSuggestion(
                type        = type,
                label       = type.label,
                description = type.promptStyle.take(70) + "…",
            )
        }
        return try {
            val preview = itemContent.take(600).replace("\"", "'")
            val prompt = """
You are helping a user choose how to turn a vault file into a mini app.
Content type: $contentType
Content preview:
\"\"\"
$preview
\"\"\"

Return ONLY a valid JSON array (no explanation, no markdown fences) with exactly 3 objects:
[{"type":"READER|INTERACTIVE|DASHBOARD","label":"2-4 word title","description":"one sentence specific to this content"}]
Order them from most useful to least useful for this content.
            """.trimIndent()

            val sb = StringBuilder()
            amplifierSession.runTurn(
                historyJson       = "[]",
                userInput         = prompt,
                userContentJson   = null,
                systemPrompt      = "Return ONLY valid JSON. No markdown. No explanation.",
                onToolStart       = { _, _ -> "" },
                onToolEnd         = { _, _ -> },
                onToken           = { token -> sb.append(token) },
                onProviderRequest = { null },
                onServerTool      = { _, _ -> },
            )

            // Strip possible markdown fences
            val raw = sb.toString().trim()
                .removePrefix("```json").removePrefix("```").removeSuffix("```").trim()

            val arr = JSONArray(raw)
            (0 until arr.length()).map { i ->
                val obj = arr.getJSONObject(i)
                RendererSuggestion(
                    type        = com.vela.app.ai.RendererType.valueOf(obj.getString("type")),
                    label       = obj.getString("label"),
                    description = obj.getString("description"),
                )
            }.takeIf { it.size == 3 } ?: fallback
        } catch (e: Exception) {
            Log.d("MiniAppViewModel", "suggestRendererTypes fallback: ${e.message}")
            fallback
        }
    }
}

// ────────────────────────────────────────────────────────────────────────────────
// Composable
// ────────────────────────────────────────────────────────────────────────────────

/**
 * Full-screen mini app host. Owns the [WebView] lifecycle, injects the Vela SDK,
 * and keeps `window.__VELA_CONTEXT__` current as theme or capabilities change.
 *
 * The file is named `MiniAppRuntime.kt`; the exported composable is `MiniAppContainer`
 * (per the design doc §5 naming convention).
 *
 * @param itemPath      Vault-relative path to the item being rendered, e.g. `"recipes/carbonara.md"`.
 * @param itemContent   Raw text content of the vault item.
 * @param contentType   Renderer content type key, e.g. `"recipe"`.
 * @param layout        `"phone"` or `"tablet"` — injected into `__VELA_CONTEXT__`.
 */
@Composable
fun MiniAppContainer(
    itemPath: String,
    itemContent: String,
    contentType: String,
    layout: String,
    modifier: Modifier = Modifier,
    viewModel: MiniAppViewModel = hiltViewModel(),
) {
    // ── Reactive state ────────────────────────────────────────────────────────
    val capabilities by viewModel.capabilities.collectAsState()
    val isDark       = isSystemInDarkTheme()
    val primaryArgb  = MaterialTheme.colorScheme.primary.toArgb()
    val primaryHex   = "#%06X".format(primaryArgb and 0xFFFFFF)
    val theme        = VelaTheme(isDark = isDark, primaryColor = primaryHex)

    val contextJson = remember(itemPath, itemContent, contentType, capabilities, isDark, primaryHex, layout) {
        buildContextJson(itemPath, itemContent, contentType, capabilities, theme, layout)
    }

    // ── JS interface — stable for the composable's lifetime ───────────────────
    val jsInterface = remember(itemPath, contentType) {
        viewModel.createJsInterface(itemPath, contentType)
    }

    DisposableEffect(jsInterface) {
        onDispose { jsInterface.cancelAllSubscriptions() }
    }

    // ── RendererState — drives which UI branch is shown ───────────────────────
    // Default: if a cached renderer exists → Ready; otherwise → Fallback (show
    // native content immediately, no LLM call). Generation is user-initiated only.
    var rendererState by remember(contentType) {
        mutableStateOf<RendererState>(
            viewModel.getRendererFile(contentType)
                ?.let { RendererState.Ready(it) }
                ?: RendererState.Fallback(contentType, itemContent)
        )
    }

    // ── Branch on state ───────────────────────────────────────────────────────
    when (val s = rendererState) {

        // ── Fallback: native content + icon-only FAB ──────────────────────────
        is RendererState.Fallback -> {
            var showTypeSheet by remember { mutableStateOf(false) }

            Box(modifier) {
                FallbackRenderer(
                    contentType = s.contentType,
                    content     = s.content,
                    modifier    = Modifier.fillMaxSize(),
                )
                FloatingActionButton(
                    onClick  = { showTypeSheet = true },
                    modifier = Modifier
                        .align(Alignment.BottomEnd)
                        .padding(16.dp),
                ) {
                    Icon(Icons.Default.AutoAwesome, contentDescription = "Generate mini app")
                }
            }

            if (showTypeSheet) {
                RendererTypeSheet(
                    viewModel      = viewModel,
                    itemContent    = itemContent,
                    contentType    = contentType,
                    onDismiss      = { showTypeSheet = false },
                    onSelect       = { type ->
                        showTypeSheet = false
                        rendererState = RendererState.Building(type)
                    },
                    onOpenExisting = {
                        showTypeSheet = false
                        viewModel.getRendererFile(contentType)?.let { file ->
                            rendererState = RendererState.Ready(file)
                        }
                    },
                )
            }
        }

        // ── Building: full-screen build log ───────────────────────────────────
        is RendererState.Building -> {
            val buildLog by viewModel.buildLog.collectAsState()

            LaunchedEffect(s.rendererType) {
                val result = viewModel.generateRenderer(
                    itemPath     = itemPath,
                    itemContent  = itemContent,
                    contentType  = contentType,
                    theme        = theme,
                    layout       = layout,
                    rendererType = s.rendererType,
                )
                rendererState = when (result) {
                    is GenerationResult.Success ->
                        viewModel.getRendererFile(contentType)
                            ?.let { RendererState.Ready(it) }
                            ?: RendererState.Fallback(contentType, itemContent)
                    is GenerationResult.Failure -> {
                        Log.w("MiniAppRuntime", "Build failed", result.cause)
                        RendererState.BuildFailed(s.rendererType, result.cause)
                    }
                }
            }

            RendererBuildScreen(
                rendererType = s.rendererType,
                contentType  = contentType,
                buildLog     = buildLog,
                onCancel     = { rendererState = RendererState.Fallback(contentType, itemContent) },
                modifier     = modifier,
            )
        }

        // ── BuildFailed: error + retry ─────────────────────────────────────────
        is RendererState.BuildFailed -> {
            RendererBuildFailedScreen(
                rendererType = s.rendererType,
                cause        = s.cause,
                onRetry      = { rendererState = RendererState.Building(s.rendererType) },
                onViewAsText = { rendererState = RendererState.Fallback(contentType, itemContent) },
                modifier     = modifier,
            )
        }

        // ── Ready / Loading: WebView ───────────────────────────────────────────
        else -> {
            AndroidView(
                factory = { ctx ->
                    WebView(ctx).apply {
                        // Wire evaluateJavascript callback back to this WebView
                        jsInterface.onEvaluateJs = { js ->
                            post { evaluateJavascript(js, null) }
                        }

                        // Register the four SDK namespaces
                        addJavascriptInterface(jsInterface.db,     "__vela_db")
                        addJavascriptInterface(jsInterface.events, "__vela_events")
                        addJavascriptInterface(jsInterface.ai,     "__vela_ai")
                        addJavascriptInterface(jsInterface.vault,  "__vela_vault")

                        settings.javaScriptEnabled = true
                        settings.domStorageEnabled = true

                        webViewClient = object : WebViewClient() {
                            override fun onPageFinished(view: WebView, url: String) {
                                // Assemble window.vela namespace + inject __VELA_CONTEXT__
                                val script = buildString {
                                    append("(function(){")
                                    append("window.vela={")
                                    append("db:window.__vela_db,")
                                    append("events:window.__vela_events,")
                                    append("ai:window.__vela_ai,")
                                    append("vault:window.__vela_vault")
                                    append("};")
                                    append("window.__VELA_CONTEXT__=")
                                    append(contextJson)
                                    append(";")
                                    append("if(typeof window.onVelaReady==='function')window.onVelaReady();")
                                    append("})();")
                                }
                                view.evaluateJavascript(script, null)
                            }
                        }

                        // Load renderer if it exists, otherwise show the loading placeholder
                        val rendererFile = viewModel.getRendererFile(contentType)
                        if (rendererFile != null) {
                            loadUrl("file://${rendererFile.absolutePath}")
                        } else {
                            loadData(LOADING_PLACEHOLDER_HTML, "text/html", "UTF-8")
                        }
                    }
                },
                update = { webView ->
                    val currentState = rendererState
                    if (currentState is RendererState.Ready) {
                        // Transition from Fallback → Ready: load renderer if not yet loaded
                        val fileUrl = "file://${currentState.rendererFile.absolutePath}"
                        if (webView.url != fileUrl) {
                            webView.loadUrl(fileUrl)
                        }
                    }
                    // Push the latest __VELA_CONTEXT__ (e.g. after theme change
                    // or after a new mini app joins the capabilities graph)
                    webView.post {
                        webView.evaluateJavascript("window.__VELA_CONTEXT__=$contextJson;", null)
                    }
                },
                modifier = modifier.fillMaxSize(),
            )
        }
    }
}

// ────────────────────────────────────────────────────────────────────────────────
// FallbackRenderer — always renders something when WebView generation fails
// ────────────────────────────────────────────────────────────────────────────────

/**
 * Native Compose fallback shown when no cached renderer exists (or generation fails).
 * Dispatches to content-type-appropriate viewers so there is never a blank screen.
 */
@Composable
private fun FallbackRenderer(
    contentType: String,
    content: String,
    modifier: Modifier = Modifier,
) {
    when (contentType) {
        "markdown" -> Box(modifier.verticalScroll(rememberScrollState()).padding(16.dp)) {
            MarkdownText(text = content, color = MaterialTheme.colorScheme.onSurface)
        }
        else -> Box(modifier.verticalScroll(rememberScrollState()).padding(16.dp)) {
            Text(text = content, style = MaterialTheme.typography.bodySmall)
        }
    }
}

// ────────────────────────────────────────────────────────────────────────────────
// RendererTypeSheet — bottom sheet for selecting renderer type
// ────────────────────────────────────────────────────────────────────────────────

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun RendererTypeSheet(
    viewModel: MiniAppViewModel,
    itemContent: String,
    contentType: String,
    onDismiss: () -> Unit,
    onSelect: (com.vela.app.ai.RendererType) -> Unit,
    onOpenExisting: () -> Unit,
) {
    // State
    var suggestions  by remember { mutableStateOf<List<RendererSuggestion>?>(null) }
    var existingFile by remember { mutableStateOf<java.io.File?>(null) }

    // Kick off both lookups when the sheet appears
    LaunchedEffect(contentType) {
        existingFile = viewModel.getRendererFile(contentType)
        suggestions  = viewModel.suggestRendererTypes(itemContent, contentType)
    }

    ModalBottomSheet(onDismissRequest = onDismiss) {
        Text(
            "What kind of mini app?",
            style    = MaterialTheme.typography.titleMedium,
            modifier = Modifier.padding(horizontal = 24.dp, vertical = 8.dp),
        )

        if (suggestions == null) {
            // Loading state
            Box(
                modifier         = Modifier
                    .fillMaxWidth()
                    .height(160.dp),
                contentAlignment = Alignment.Center,
            ) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    CircularProgressIndicator()
                    Spacer(Modifier.height(12.dp))
                    Text(
                        "Analysing your content…",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
            }
        } else {
            // Existing app row (only shown if a renderer file exists)
            existingFile?.let {
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 16.dp, vertical = 4.dp)
                        .clickable { onOpenExisting() },
                    colors = CardDefaults.cardColors(
                        containerColor = MaterialTheme.colorScheme.primaryContainer,
                    ),
                ) {
                    ListItem(
                        headlineContent   = { Text("Open existing mini app") },
                        supportingContent = { Text("View the $contentType app you already built.") },
                        leadingContent    = {
                            Icon(
                                Icons.Default.OpenInNew,
                                contentDescription = null,
                                tint = MaterialTheme.colorScheme.onPrimaryContainer,
                            )
                        },
                        colors = ListItemDefaults.colors(
                            containerColor = androidx.compose.ui.graphics.Color.Transparent,
                        ),
                    )
                }
                HorizontalDivider(modifier = Modifier.padding(vertical = 8.dp))
            }

            // AI-personalised choices
            suggestions!!.forEach { suggestion ->
                ListItem(
                    headlineContent   = { Text(suggestion.label) },
                    supportingContent = { Text(suggestion.description) },
                    leadingContent    = {
                        Icon(
                            imageVector = when (suggestion.type) {
                                com.vela.app.ai.RendererType.READER      -> Icons.Default.MenuBook
                                com.vela.app.ai.RendererType.INTERACTIVE -> Icons.Default.TouchApp
                                com.vela.app.ai.RendererType.DASHBOARD   -> Icons.Default.Dashboard
                            },
                            contentDescription = null,
                        )
                    },
                    modifier = Modifier.clickable { onSelect(suggestion.type) },
                )
            }
        }

        Spacer(Modifier.height(32.dp))
    }
}

// ────────────────────────────────────────────────────────────────────────────────
// RendererBuildScreen — full-screen streaming build log
// ────────────────────────────────────────────────────────────────────────────────

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun RendererBuildScreen(
    rendererType: com.vela.app.ai.RendererType,
    contentType: String,
    buildLog: String,
    onCancel: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val listState  = rememberLazyListState()
    val tokenCount = buildLog.length

    // Auto-scroll to bottom as tokens arrive
    LaunchedEffect(tokenCount) {
        if (tokenCount > 0) listState.animateScrollToItem(0)
    }

    // Phase label based on progress
    val phase = when {
        tokenCount == 0    -> "Starting…"
        tokenCount < 200   -> "Analysing your ${contentType}…"
        tokenCount < 800   -> "Designing the layout…"
        tokenCount < 2_000 -> "Writing components…"
        else               -> "Finalising…"
    }

    Column(modifier.fillMaxSize()) {
        // Header
        TopAppBar(
            title = {
                Column {
                    Text("Building ${rendererType.label}", style = MaterialTheme.typography.titleMedium)
                    Text(
                        phase,
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
            },
            navigationIcon = {
                IconButton(onClick = onCancel) {
                    Icon(Icons.Default.Close, contentDescription = "Cancel")
                }
            },
        )
        LinearProgressIndicator(modifier = Modifier.fillMaxWidth())

        // Live build log (newest lines at bottom; rendered reversed in a reversed LazyColumn)
        val lines = buildLog.takeLast(4_000).lines()
        LazyColumn(
            state          = listState,
            reverseLayout  = true,
            modifier       = Modifier
                .weight(1f)
                .fillMaxWidth()
                .background(MaterialTheme.colorScheme.surface),
            contentPadding = PaddingValues(horizontal = 12.dp, vertical = 8.dp),
        ) {
            items(lines.reversed()) { line ->
                Text(
                    text  = line,
                    style = MaterialTheme.typography.bodySmall.copy(
                        fontFamily = androidx.compose.ui.text.font.FontFamily.Monospace,
                    ),
                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.8f),
                )
            }
        }

        // Footer
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp, vertical = 8.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
        ) {
            TextButton(onClick = onCancel) { Text("Cancel") }
            Text(
                "$tokenCount chars",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
        }
    }
}

// ────────────────────────────────────────────────────────────────────────────────
// RendererBuildFailedScreen — error screen with retry / view-as-text
// ────────────────────────────────────────────────────────────────────────────────

@Composable
private fun RendererBuildFailedScreen(
    rendererType: com.vela.app.ai.RendererType,
    cause: Throwable,
    onRetry: () -> Unit,
    onViewAsText: () -> Unit,
    modifier: Modifier = Modifier,
) {
    Column(
        modifier            = modifier.fillMaxSize().padding(32.dp),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Icon(
            Icons.Default.ErrorOutline,
            contentDescription = null,
            tint     = MaterialTheme.colorScheme.error,
            modifier = Modifier.size(48.dp),
        )
        Spacer(Modifier.height(16.dp))
        Text("Build failed", style = MaterialTheme.typography.titleMedium)
        Spacer(Modifier.height(8.dp))
        Text(
            cause.message ?: "Unknown error",
            style     = MaterialTheme.typography.bodySmall,
            color     = MaterialTheme.colorScheme.onSurfaceVariant,
            textAlign = TextAlign.Center,
        )
        Spacer(Modifier.height(24.dp))
        Button(onClick = onRetry) { Text("Try again") }
        Spacer(Modifier.height(8.dp))
        OutlinedButton(onClick = onViewAsText) { Text("View as text") }
    }
}

// ────────────────────────────────────────────────────────────────────────────────
// Private helpers
// ────────────────────────────────────────────────────────────────────────────────

/**
 * Serialises all inputs into the `__VELA_CONTEXT__` JSON object that is injected
 * into every renderer after page load (design doc §2).
 *
 * `globalCollections` is an empty object for now — RendererGenerator populates it
 * with actual global/type snapshots at generation time (Task 6). Keeping it as `{}`
 * here keeps the runtime injection fast and avoids an additional DB round-trip on
 * every page load.
 */
private fun buildContextJson(
    itemPath: String,
    itemContent: String,
    contentType: String,
    capabilities: List<MiniAppRegistryEntity>,
    theme: VelaTheme,
    layout: String,
): String {
    val capsArray = JSONArray()
    capabilities.forEach { entity ->
        capsArray.put(JSONObject().apply {
            put("type", entity.contentType)
            put("provides", runCatching { JSONArray(entity.provides) }.getOrElse { JSONArray() })
            put("consumes", runCatching { JSONArray(entity.consumes) }.getOrElse { JSONArray() })
        })
    }
    return JSONObject().apply {
        put("itemPath",          itemPath)
        put("itemContent",       itemContent)
        put("contentType",       contentType)
        put("capabilities",      capsArray)
        put("globalCollections", JSONObject())
        put("theme", JSONObject().apply {
            put("isDark",       theme.isDark)
            put("primaryColor", theme.primaryColor)
        })
        put("layout", layout)
    }.toString()
}

private const val LOADING_PLACEHOLDER_HTML = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  body{margin:0;display:flex;align-items:center;justify-content:center;
       min-height:100vh;font-family:sans-serif;background:#121212;color:#888;}
  p{font-size:14px;letter-spacing:.5px;}
</style></head>
<body><p>Generating renderer…</p></body>
</html>"""
